USE DW_SEGURADORA;
SET LANGUAGE PORTUGUESE;

--TRUNCATE TABLE DW_SEGURADORA..DM_TEMPO

DECLARE @DATA_INICIO DATE = '2005-01-01'
DECLARE @DATA_FIM DATE = '2027-12-31'

INSERT INTO DM_TEMPO ([DATA],[ANO],[MES],[DIA],[DIA_SEMANA],[DIA_SEMANA_NUM],[MES_NOME],[TRIMESTRE],[SEMESTRE],[ANO_MES],[DIA_ANO],[DATA_DESC],[DIA_UTIL]) VALUES('0001-01-01', -1, -1, -1, 'N/A', -1, 'N/A', -1, -1, '0001-01', -1, 'N/A', -1)

WHILE @DATA_INICIO <= @DATA_FIM
BEGIN
	INSERT INTO DM_TEMPO (
		[DATA],
		[ANO],
		[MES],
		[DIA],
		[DIA_SEMANA],
		[DIA_SEMANA_NUM],
		[MES_NOME],
		[TRIMESTRE],
		[SEMESTRE],
		[ANO_MES],
		[DIA_ANO],
		[DATA_DESC],
		[DIA_UTIL]
	)
	SELECT
		@DATA_INICIO,
		YEAR(@DATA_INICIO),
		MONTH(@DATA_INICIO),
		DAY(@DATA_INICIO),
		UPPER(DATENAME(WEEKDAY, @DATA_INICIO)),
		DATEPART(WEEKDAY, @DATA_INICIO),
		UPPER(DATENAME(MONTH, @DATA_INICIO)),
		DATEPART(QUARTER, @DATA_INICIO),
		CASE WHEN MONTH(@DATA_INICIO) <= 6 THEN 1 ELSE 2 END,
		FORMAT(@DATA_INICIO, 'yyyy-MM'),
		DATEPART(DAYOFYEAR, @DATA_INICIO),
		UPPER(DATENAME(WEEKDAY, @DATA_INICIO) + ', ' + CONVERT(NVARCHAR, DAY(@DATA_INICIO)) + ' DE ' + DATENAME(MONTH, @DATA_INICIO) + ' DE ' + CONVERT(NVARCHAR, YEAR(@DATA_INICIO))),
		CASE WHEN DATEPART(WEEKDAY, @DATA_INICIO) BETWEEN 2 AND 6 THEN 1 ELSE 0 END;

	SET @DATA_INICIO = DATEADD(DAY, 1, @DATA_INICIO);
END